In [1]:
import pandas as pd

In [2]:
data = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Anand', 'Rahul', 'Priya', 'John', 'Sneha'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [80000, 55000, 90000, 75000, 60000],
    'Experience': [5, 2, 7, 4, 3]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   Employee_ID   Name Department  Salary  Experience
0          101  Anand         IT   80000           5
1          102  Rahul         HR   55000           2
2          103  Priya         IT   90000           7
3          104   John    Finance   75000           4
4          105  Sneha         HR   60000           3

In [6]:
#employee with salary >70000

df[df['Salary']>70000]

   Employee_ID   Name Department  Salary  Experience
0          101  Anand         IT   80000           5
2          103  Priya         IT   90000           7
3          104   John    Finance   75000           4

In [ ]:
select * from emp where sal>70000

In [7]:
#employee who belongs to IT department

df[df['Department']=='IT']

   Employee_ID   Name Department  Salary  Experience
0          101  Anand         IT   80000           5
2          103  Priya         IT   90000           7

In [ ]:
select * from emp where Department ='IT'

In [8]:
#IT employeee whose salary is > 85000
df[(df['Department']=='IT') & (df['Salary']>85000)]

   Employee_ID   Name Department  Salary  Experience
2          103  Priya         IT   90000           7

In [ ]:
select * from emp where Department ='IT' and Salary > 85000

In [ ]:
#employee belonging to IT or Finance department
select * from emp where Department in ('IT','Finance')

In [9]:
df[df['Department'].isin(['IT','Finance'])]

   Employee_ID   Name Department  Salary  Experience
0          101  Anand         IT   80000           5
2          103  Priya         IT   90000           7
3          104   John    Finance   75000           4

In [ ]:
#employee whose salary is in between 60000 and 85000
select * from emp where Salary BETWEEN 60000 AND 70000

In [11]:
df[df['Salary'].between(60000,85000)]

   Employee_ID   Name Department  Salary  Experience
0          101  Anand         IT   80000           5
3          104   John    Finance   75000           4
4          105  Sneha         HR   60000           3

In [12]:
#NAme starting with 'A'

df[df['Name'].str.startswith('A')]

   Employee_ID   Name Department  Salary  Experience
0          101  Anand         IT   80000           5

In [13]:
df

   Employee_ID   Name Department  Salary  Experience
0          101  Anand         IT   80000           5
1          102  Rahul         HR   55000           2
2          103  Priya         IT   90000           7
3          104   John    Finance   75000           4
4          105  Sneha         HR   60000           3

In [ ]:
select * from emp where Name like 'A%'

In [14]:
#Names containing 'h'

df[df['Name'].str.contains('h')]

   Employee_ID   Name Department  Salary  Experience
1          102  Rahul         HR   55000           2
3          104   John    Finance   75000           4
4          105  Sneha         HR   60000           3

In [15]:
df.query('Salary >70000 and Experience>=5')

   Employee_ID   Name Department  Salary  Experience
0          101  Anand         IT   80000           5
2          103  Priya         IT   90000           7

In [ ]:
select * from emp where salary>70000 and exp >=5

In [ ]:
#specific column after filtering

In [17]:
df[df['Salary']>70000][['Name','Salary']]

    Name  Salary
0  Anand   80000
2  Priya   90000
3   John   75000

In [18]:
df

   Employee_ID   Name Department  Salary  Experience
0          101  Anand         IT   80000           5
1          102  Rahul         HR   55000           2
2          103  Priya         IT   90000           7
3          104   John    Finance   75000           4
4          105  Sneha         HR   60000           3

In [21]:
df.rename(columns={'Name':'Full_Name','Employee_ID':'Emp_ID'},inplace=True)

In [22]:
df

   Emp_ID Full_Name Department  Salary  Experience
0     101     Anand         IT   80000           5
1     102     Rahul         HR   55000           2
2     103     Priya         IT   90000           7
3     104      John    Finance   75000           4
4     105     Sneha         HR   60000           3

In [23]:
df['Bonus']=10000

In [24]:
df

   Emp_ID Full_Name Department  Salary  Experience  Bonus
0     101     Anand         IT   80000           5  10000
1     102     Rahul         HR   55000           2  10000
2     103     Priya         IT   90000           7  10000
3     104      John    Finance   75000           4  10000
4     105     Sneha         HR   60000           3  10000

In [25]:
df['Bonus_updated']= df['Salary']*0.10

In [26]:
df

   Emp_ID Full_Name Department  Salary  Experience  Bonus  Bonus_updated
0     101     Anand         IT   80000           5  10000         8000.0
1     102     Rahul         HR   55000           2  10000         5500.0
2     103     Priya         IT   90000           7  10000         9000.0
3     104      John    Finance   75000           4  10000         7500.0
4     105     Sneha         HR   60000           3  10000         6000.0

In [ ]:
SELECT *, Salary*0.10 As Bonus From Employee

In [27]:
df['Net_Salary'] = df['Salary'] + df['Bonus']

In [28]:
df

,Emp_ID,Full_Name,Department,Salary,Experience,Bonus,Bonus_updated,Net_Salary
0,101,Anand,IT,80000,5,10000,8000.0,90000
1,102,Rahul,HR,55000,2,10000,5500.0,65000
2,103,Priya,IT,90000,7,10000,9000.0,100000
3,104,John,Finance,75000,4,10000,7500.0,85000
4,105,Sneha,HR,60000,3,10000,6000.0,70000

In [29]:
# employee earning more then 75000 are considered high salary employees

import numpy as np
df['Category'] = np.where(df['Salary']>75000,'High','Normal')

In [30]:
df

,Emp_ID,Full_Name,Department,Salary,Experience,Bonus,Bonus_updated,Net_Salary,Category
0,101,Anand,IT,80000,5,10000,8000.0,90000,High
1,102,Rahul,HR,55000,2,10000,5500.0,65000,Normal
2,103,Priya,IT,90000,7,10000,9000.0,100000,High
3,104,John,Finance,75000,4,10000,7500.0,85000,Normal
4,105,Sneha,HR,60000,3,10000,6000.0,70000,Normal

In [31]:
def grade(salary):
    if salary>=85000:
        return 'A'
    elif salary >=70000:
        return 'B'

    else:
        return 'C'

In [32]:
grade(789000)

'A'

In [33]:
df['Grade'] = df['Salary'].apply(grade)

In [34]:
df

,Emp_ID,Full_Name,Department,Salary,Experience,Bonus,Bonus_updated,Net_Salary,Category,Grade
0,101,Anand,IT,80000,5,10000,8000.0,90000,High,B
1,102,Rahul,HR,55000,2,10000,5500.0,65000,Normal,C
2,103,Priya,IT,90000,7,10000,9000.0,100000,High,A
3,104,John,Finance,75000,4,10000,7500.0,85000,Normal,B
4,105,Sneha,HR,60000,3,10000,6000.0,70000,Normal,C

In [35]:
df['Salary'] = df['Salary']*1.15

In [36]:
df

,Emp_ID,Full_Name,Department,Salary,Experience,Bonus,Bonus_updated,Net_Salary,Category,Grade
0,101,Anand,IT,92000.0,5,10000,8000.0,90000,High,B
1,102,Rahul,HR,63250.0,2,10000,5500.0,65000,Normal,C
2,103,Priya,IT,103500.0,7,10000,9000.0,100000,High,A
3,104,John,Finance,86250.0,4,10000,7500.0,85000,Normal,B
4,105,Sneha,HR,69000.0,3,10000,6000.0,70000,Normal,C

In [ ]:
UPDATE EMPLOYEE
set salary = salary * 1.15

In [38]:
df.loc[df['Department']=='IT', 'Salary']=df['Salary']+5000

In [39]:
df

,Emp_ID,Full_Name,Department,Salary,Experience,Bonus,Bonus_updated,Net_Salary,Category,Grade
0,101,Anand,IT,97000.0,5,10000,8000.0,90000,High,B
1,102,Rahul,HR,63250.0,2,10000,5500.0,65000,Normal,C
2,103,Priya,IT,108500.0,7,10000,9000.0,100000,High,A
3,104,John,Finance,86250.0,4,10000,7500.0,85000,Normal,B
4,105,Sneha,HR,69000.0,3,10000,6000.0,70000,Normal,C

In [ ]:
UPDATE EMPLOYEE
set salary = salary +5000
where Department ='IT'

In [42]:
data = {
    'Name':['Rahul','Rishi','Charles','John'],
    'Age':[25,26,56,34]
}

In [43]:
df1= pd.DataFrame(data)

In [44]:
df1

      Name  Age
0    Rahul   25
1    Rishi   26
2  Charles   56
3     John   34

In [51]:
df1['Age_group']=df1['Age'].apply(lambda x: "Senior" if x>35  else "Junior")

In [53]:
df1['age_group'] = np.where(df1['Age'] > 35, 'senior', 'junior')

In [54]:
df1

      Name  Age age_group Age_group
0    Rahul   25    junior    Junior
1    Rishi   26    junior    Junior
2  Charles   56    senior    Senior
3     John   34    junior    Junior

In [92]:
import pandas as pd
import numpy as np

data = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Employee_Name': ['Anand', 'Rahul', None, 'John', 'Priya'],
    'Department': ['IT', 'HR', 'Finance', None, 'IT'],
    'Salary': [80000, np.nan, 90000, 75000, np.nan]
}

In [93]:
df2 = pd.DataFrame(data)

In [87]:
df2

   Employee_ID Employee_Name Department   Salary
0          101         Anand         IT  80000.0
1          102         Rahul         HR      NaN
2          103          None    Finance  90000.0
3          104          John       None  75000.0
4          105         Priya         IT      NaN

In [88]:
df2.isnull().sum()

Employee_ID      0
Employee_Name    1
Department       1
Salary           2
dtype: int64

In [ ]:
SELECT
SUM(CASE WHEN Employee_Name IS NULL THEN 1 ELSE 0 END) AS Missing_Name,
SUM(CASE WHEN Salary IS NULL THEN 1 ELSE 0 END) AS Missing_Salary
FROM Employee;

In [94]:
cleaned_df=df2.dropna(subset=['Employee_Name'])

In [63]:
df2

   Employee_ID Employee_Name Department   Salary
0          101         Anand         IT  80000.0
1          102         Rahul         HR      NaN
2          103          None    Finance  90000.0
3          104          John       None  75000.0
4          105         Priya         IT      NaN

In [90]:
cleaned_df

   Employee_ID Employee_Name Department   Salary
0          101         Anand         IT  80000.0
1          102         Rahul         HR      NaN
3          104          John       None  75000.0
4          105         Priya         IT      NaN

In [74]:
cleaned_df['Salary']=cleaned_df['Salary'].fillna(0)

C:\Users\prach\AppData\Local\Temp\ipykernel_21884\783540156.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df['Salary']=cleaned_df['Salary'].fillna(0)

In [95]:
cleaned_df

   Employee_ID Employee_Name Department   Salary
0          101         Anand         IT  80000.0
1          102         Rahul         HR      NaN
3          104          John       None  75000.0
4          105         Priya         IT      NaN

In [96]:
mean_sal = cleaned_df['Salary'].mean()

In [97]:
mean_sal

77500.0

In [98]:
cleaned_df['Salary']=cleaned_df['Salary'].fillna(mean_sal)

C:\Users\prach\AppData\Local\Temp\ipykernel_21884\825066154.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df['Salary']=cleaned_df['Salary'].fillna(mean_sal)

In [99]:
cleaned_df

   Employee_ID Employee_Name Department   Salary
0          101         Anand         IT  80000.0
1          102         Rahul         HR  77500.0
3          104          John       None  75000.0
4          105         Priya         IT  77500.0