In [1]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\prach\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\prach\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\prach\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\prach\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\prach\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\prach\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\prach\AppData\Local\Temp\ipykernel_24628\1507830365.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\__init__.py", line 38, in <module>
    from pandas.compat import (
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 29, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\prach\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\prach\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\prach\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\prach\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\prach\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\prach\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\prach\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\prach\AppData\Local\Temp\ipykernel_24628\1507830365.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\prach\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\prach\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\prach\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\prach\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\prach\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\prach\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\prach\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\prach\AppData\Local\Temp\ipykernel_24628\1507830365.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 53, in <module>
    from pandas.core import (
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\prach\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\prach\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\prach\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\prach\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\prach\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\prach\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\prach\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\prach\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\prach\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\prach\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\prach\AppData\Local\Temp\ipykernel_24628\1507830365.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 67, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 61, in <module>
    from pandas.core import (
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\prach\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\prach\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\prach\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

2.4.6
2.3.3

In [2]:
!pip uninstall numpy -y
!pip install numpy==1.26.4

Found existing installation: numpy 2.4.6
Uninstalling numpy-2.4.6:
  Successfully uninstalled numpy-2.4.6

WARNING: Ignoring invalid distribution ~andas (C:\Users\prach\AppData\Roaming\Python\Python311\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\prach\AppData\Roaming\Python\Python311\site-packages)
WARNING: Failed to remove contents in a temporary directory 'C:\Users\prach\anaconda3\Lib\site-packages\~umpy.libs'.
You can safely remove it manually.
WARNING: Failed to remove contents in a temporary directory 'C:\Users\prach\anaconda3\Lib\site-packages\~umpy'.
You can safely remove it manually.

Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
Installing collected packages: numpy
Successfully installed numpy-1.26.4

WARNING: Ignoring invalid distribution ~andas (C:\Users\prach\AppData\Roaming\Python\Python311\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\prach\AppData\Roaming\Python\Python311\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\prach\AppData\Roaming\Python\Python311\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
altair 4.2.2 requires pandas>=0.18, which is not installed.
bokeh 3.3.4 requires pandas>=1.2, which is not installed.
datashader 0.16.0 requires numba, which is not installed.
datashader 0.16.0 requires pandas, which is not installed.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
great-expectations 1.7.0 requires pandas>=1.3.0; python_version >= "3.10", which is not installed.
holoviews 1.18.3 requires pandas>=0.20.0, which is not installed.
hvplot 0.9.2 requires pandas, which is not installed.
librosa 0.10.2.post1 requires numba>=0.51.0, which is not installed.
panel 1.3.8 requires pandas>=1.2, which is not installed.
phik 0.12.4 requires pandas>=0.25.1, which is not installed.
seaborn 0.12.2 requires pandas>=0.25, which is not installed.
statsmodels 0.14.0 requires pandas>=1.0, which is not installed.
streamlit 1.47.0 requires pandas<3,>=1.4.0, which is not installed.
sweetviz 2.3.1 requires pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3, which is not installed.
xarray 2023.6.0 requires pandas>=1.4, which is not installed.
torchvision 0.19.0 requires torch==2.4.0, but you have torch 2.4.1 which is incompatible.
WARNING: Ignoring invalid distribution ~andas (C:\Users\prach\AppData\Roaming\Python\Python311\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\prach\AppData\Roaming\Python\Python311\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\prach\AppData\Roaming\Python\Python311\site-packages)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

1.26.4
2.3.3

In [2]:
prices = pd.Series([250, 480, 125, 999]) 
print(prices)

0    250
1    480
2    125
3    999
dtype: int64

In [3]:
prices

0    250
1    480
2    125
3    999
dtype: int64

In [4]:
students = pd.DataFrame({"Student_name":["Rahul","Priya","Amit","Sneha","Rohan"],
                         "Maths":[85,92,78,95,88],
                         "Science":[98,35,78,27,99],
                         "City":["Delhi","Mumbai","Ahemdabad","Pune","Noida"]})

In [5]:
students

  Student_name  Maths  Science       City
0        Rahul     85       98      Delhi
1        Priya     92       35     Mumbai
2         Amit     78       78  Ahemdabad
3        Sneha     95       27       Pune
4        Rohan     88       99      Noida

In [7]:
students.head(2)

  Student_name  Maths  Science    City
0        Rahul     85       98   Delhi
1        Priya     92       35  Mumbai

In [8]:
students.tail(2)

  Student_name  Maths  Science   City
3        Sneha     95       27   Pune
4        Rohan     88       99  Noida

In [9]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_name  5 non-null      object
 1   Maths         5 non-null      int64
 2   Science       5 non-null      int64
 3   City          5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [11]:
students["Maths"][0]

85

In [16]:
students[["Student_name","Maths"]]

  Student_name  Maths
0        Rahul     85
1        Priya     92
2         Amit     78
3        Sneha     95
4        Rohan     88

In [17]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Sneha"],
    "Maths": [85, 92, 78, 95],
    "Science": [90, 88, 80, 91]
})

print(df)

    Name  Maths  Science
0  Rahul     85       90
1  Priya     92       88
2   Amit     78       80
3  Sneha     95       91

In [18]:
df

    Name  Maths  Science
0  Rahul     85       90
1  Priya     92       88
2   Amit     78       80
3  Sneha     95       91

In [19]:
df.columns

Index(['Name', 'Maths', 'Science'], dtype='object')

In [21]:
print(df.index)

RangeIndex(start=0, stop=4, step=1)

In [22]:
df.index = ["S101","S102","S103","S104"]

In [23]:
df

       Name  Maths  Science
S101  Rahul     85       90
S102  Priya     92       88
S103   Amit     78       80
S104  Sneha     95       91

In [24]:
df.loc["S102"]

Name       Priya
Maths         92
Science       88
Name: S102, dtype: object

In [25]:
df.loc["S102","Maths"]

92

In [26]:
df.loc[["S101","S104"]]

       Name  Maths  Science
S101  Rahul     85       90
S104  Sneha     95       91

In [27]:
df.loc[["S101","S104"],["Name","Maths"]]

       Name  Maths
S101  Rahul     85
S104  Sneha     95

In [28]:
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit"],
    "Maths": [85, 92, 78],
    "Science": [90, 87, 80]
})

print(df1)

    Name  Maths  Science
0  Rahul     85       90
1  Priya     92       87
2   Amit     78       80

In [29]:
df1.loc[1]

Name       Priya
Maths         92
Science       87
Name: 1, dtype: object

In [30]:
df1.loc[1,"Maths"]

92

In [ ]:
.iloc

In [31]:
df

       Name  Maths  Science
S101  Rahul     85       90
S102  Priya     92       88
S103   Amit     78       80
S104  Sneha     95       91

In [32]:
df.iloc[1]

Name       Priya
Maths         92
Science       88
Name: S102, dtype: object

In [33]:
df.iloc[2,1]

78

In [34]:
df.iloc[0:2]

       Name  Maths  Science
S101  Rahul     85       90
S102  Priya     92       88

In [35]:
df.iloc[1:3,0:2]

       Name  Maths
S102  Priya     92
S103   Amit     78

In [36]:
df = pd.DataFrame({
    "Emp_ID":[101,102,103,104],
    "Name":["Anand","Riya","Kabir","Sara"],
    "Salary":[85000,75000,95000,90000]
})

In [37]:
df

   Emp_ID   Name  Salary
0     101  Anand   85000
1     102   Riya   75000
2     103  Kabir   95000
3     104   Sara   90000

In [38]:
df.set_index("Emp_ID",inplace=True)

In [39]:
df

         Name  Salary
Emp_ID
101     Anand   85000
102      Riya   75000
103     Kabir   95000
104      Sara   90000

In [40]:
df.loc[103]

Name      Kabir
Salary    95000
Name: 103, dtype: object

In [43]:
df1=df.reset_index()

In [44]:
df1

   Emp_ID   Name  Salary
0     101  Anand   85000
1     102   Riya   75000
2     103  Kabir   95000
3     104   Sara   90000

In [45]:
df1[df1["Salary"]>85000]

   Emp_ID   Name  Salary
2     103  Kabir   95000
3     104   Sara   90000

In [51]:
df2=pd.read_csv(r"C:\Users\prach\Downloads\test (2).csv")

In [52]:
df2

   Emp_ID   Name Department  Salary
0     101  Anand         IT   85000
1     102   Riya         HR   75000
2     103  Kabir         IT   95000
3     104   Sara    Finance   90000

In [53]:
df3 = pd.read_excel("employee.xlsx")

In [54]:
df3

   EmployeeID FirstName LastName  DepartmentID  Salary   HireDate
0           1      John      Doe            10    5500 2020-01-15
1           2      Jane    Smith            20    7000 2018-03-25
2           3     Alice  Johnson            10    4800 2021-07-10
3           4       Bob    Brown            30    6200 2019-11-05
4           5   Charlie    Davis            20    7200 2017-05-20
5           6       Eve   Wilson            30    4000 2022-02-14

In [55]:
df3[["FirstName","LastName","HireDate"]]

  FirstName LastName   HireDate
0      John      Doe 2020-01-15
1      Jane    Smith 2018-03-25
2     Alice  Johnson 2021-07-10
3       Bob    Brown 2019-11-05
4   Charlie    Davis 2017-05-20
5       Eve   Wilson 2022-02-14

In [56]:
df4=pd.read_csv("tab_ex.txt",sep="|")

In [57]:
df4

   Emp_ID   Name Department  Salary
0     101  Anand         IT   85000
1     102   Riya         HR   75000
2     103  Kabir         IT   95000
3     104   Sara    Finance   90000

In [60]:
df5=pd.read_json("json_data.json")

In [61]:
df5

   Emp_ID   Name Department  Salary
0     101  Anand         IT   85000
1     102   Riya         HR   75000
2     103  Kabir         IT   95000

In [62]:
df5.shape

(3, 4)

In [63]:
df5.columns

Index(['Emp_ID', 'Name', 'Department', 'Salary'], dtype='object')

In [64]:
df5.index

RangeIndex(start=0, stop=3, step=1)

In [65]:
df5.dtypes

Emp_ID         int64
Name          object
Department    object
Salary         int64
dtype: object

In [66]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      3 non-null      int64
 1   Name        3 non-null      object
 2   Department  3 non-null      object
 3   Salary      3 non-null      int64
dtypes: int64(2), object(2)
memory usage: 228.0+ bytes

In [68]:
df5.describe()

       Emp_ID   Salary
count     3.0      3.0
mean    102.0  85000.0
std       1.0  10000.0
min     101.0  75000.0
25%     101.5  80000.0
50%     102.0  85000.0
75%     102.5  90000.0
max     103.0  95000.0